MODEL:


TRAIN:
  train_data_dir: [
    '/data/gjh8760/Dataset/STISR/TextZoom/train1',
    '/data/gjh8760/Dataset/STISR/TextZoom/train2',
    '/data/gjh8760/Dataset/STISR/kor_cropped_text/lmdb_training',
  ]
  batch_size: 512
  width: 128
  height: 32
  epochs: 500
  cuda: True
  ngpu: 1
  workers: 8
  resume: ''
  ckpt_dir: './ckpt'
  voc_type: 'all' #'digits lower upper all'
  saveInterval: 200
  displayInterval: 50 #display loss
  adadelta: False
  lr: 0.001
  adam: True
  optimizer: "Adam"
  beta1: 0.5
  manualSeed: 1234
  max_len: 100
  keep_ratio: False
  down_sample_scale: 2

  VAL:
    val_data_dir: [
      '/data/gjh8760/Dataset/STISR/TextZoom/test/easy',
      '/data/gjh8760/Dataset/STISR/TextZoom/test/medium',
      '/data/gjh8760/Dataset/STISR/TextZoom/test/hard',
      '/data/gjh8760/Dataset/STISR/kor_cropped_text/lmdb_evaluation',
    ]
    n_vis: 10
    vis_dir: 'demo'
    valInterval: 200 #-1, val at the end of epoch
    rec_pretrained: './models_str/aster/demo.pth.tar'
    moran_pretrained: './models_str/moran/demo.pth'
    crnn_pretrained: './models_str/crnn/crnn.pth'
    cdistnet_eng_pretrained: './models_str/cdistnet_eng/epoch9_best_acc.pth'
    cdistnet_kor_pretrained: './models_str/cdistnet_kor/epoch10_best_acc.pth'
    cdistnet_all_pretrained: './models_str/cdistnet_all/epoch10_best_acc.pth'

TEST:
  checkpoint: ''
  test_data_dir: [
    ]

CONVERT:
  image_dir:
  lmdb_dir:
  n_convert: 10
